qa/tasks: use spaces intead of tabs for indent
to address the errors of
```
TabError: inconsistent use of tabs and spaces in indentation
```

somehow in master, we are using spaces instead of tabs, so this change
is not cherry-picked from master.

Signed-off-by: Kefu Chai <kchai@redhat.com>