qa/cephfs: to be python3 compatible
Fixes the errors like:
TypeError: a bytes-like object is required, not 'str'

Signed-off-by: Xiubo Li <xiubli@redhat.com>