qa/tasks/ceph: py3 compatibility
Addresses:
  TypeError: 'dict_values' object is not subscriptable

Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>
(cherry picked from commit fc5662957b19e03ac4bd323d94ee2f3dc302c792)